name: penguin-subtitle-player
base: core18
version: '1.4.0'
summary: An open-source, cross-platform standalone subtitle player # 79 char long summary
description: |
  You download the subtitle file (.srt, .ssa, .ass) file from any sites you like and load it into the subtitle player. 
  The subtitle player provides a translucent window which always stays on the top so that subtitles can be shown on top of the video without blocking anything.
  With Penguin Subtitle Player, just open your favorite online streaming site, load the subtitle file into the player, and enjoy.

grade: stable
confinement: strict
architectures:
#  - build-on: s390x and below not available due to kde-neon extension not supporting them
#  - build-on: ppc64el
#  - build-on: arm64
#  - build-on: armhf
#  - build-on: i386
  - build-on: amd64


apps:
  penguin-subtitle-player:
    extensions:
      - kde-neon
    command: bin/PenguinSubtitlePlayer
    plugs: [home]
    
parts:
  penguin-subtitle-player:
    source: https://github.com/carsonip/Penguin-Subtitle-Player.git
    options:
     - "target.path=/bin"
     - "INSTALLS+=target"
    plugin: qmake
    project-files: [PenguinSubtitlePlayer.pro]
