name: penguin-subtitle-player # you probably want to 'snapcraft register <name>'
base: core18
version: '1.3.0'
summary: An open-source, cross-platform standalone subtitle player # 79 char long summary
description: |
  You download the subtitle file (.srt, .ssa, .ass) file from any sites you like and load it into the subtitle player. 
  The subtitle player provides a translucent window which always stays on the top so that subtitles can be shown on top of the video without blocking anything.
  With Penguin Subtitle Player, just open your favorite online streaming site, load the subtitle file into the player, and enjoy.

grade: stable
confinement: strict

apps:
  penguin-subtitle-player:
    extensions:
      - kde-neon
    command: bin/PenguinSubtitlePlayer
    plugs: [home]
    
parts:
  penguin-subtitle-player:
    source: https://github.com/carsonip/Penguin-Subtitle-Player.git
    options:
     - "target.path=/bin"
     - "INSTALLS+=target"
    plugin: qmake
    project-files: [PenguinSubtitlePlayer.pro]
